### ISSUE TITLE
[BUG] 后台自动发送莫名其妙的预设文本

### ISSUE THREAD

**Issue by Admmmmmmin** [lss233/kirara-ai#1124]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
在 chatgpt 容器重启之后、发送第一条消息时，后台可以看到一批莫名其妙的预设， 在我把预设文件夹清空之后仍然会有预设发送，账号也因此达到了 OpenAI 的速率限额。

**运行环境:**  
- 操作系统：Cent OS 7
- Docker： ？
- 项目版本：latest

**相关代码**
```
  chatgpt:
    image: lss233/chatgpt-mirai-qq-bot:browser-version
    restart: always
    environment:
      LANG: 'C.UTF-8'
    volumes:
      - ./config.cfg:/app/config.cfg
      - ./data:/app/data
      - ./presets:/app/presets
      # - ./fonts:/app/fonts # 如果你想自定义字体，就解除注释
```

**复现步骤**  
- ``` docker-compose restart chatgpt ```
- 发送任意消息，比如“你好”
- ![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/78294316/fdf3f241-4192-4ad8-9bf8-325faca41bda)
